(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 0.00,
	manifest: []
};



lib.ssMetadata = [];


// symbols:



(lib.kist_r = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ACxhAQgDgBgCAAQgDgBgDAAQgFgBgFgBIAYgRIAFgIIAxAAIgQATIAfAAIAYAnIgZAWIAcAAIAAA4IAPAAIgZAzIgSAbIgoAAIAAgXIAugIIAAgnIgZANIgRgaIABAAIAegbIACgCIACADIgEgBIgWgLQAAAAAAgBQgCgJgDgIQAAgCgBgBIANgRQAMgRgGAAQgEAAgEABQgVAAgDAAIgLgFQgFgDgJgCgAD3AMIAIAVIAAgRgADHhEIgFAAQgHAEgKAAAB+gqIgFAAQgHAEgKAAQgCgBgCAAQgEgBgDAAQgFgBgEgBQgBAAgBAAQgHgCgFgEQgBgDgBgDQgJgSgSgTQgYgbgOABQgbAChUAAQgvAAgUAAQgLABgCAAQgCAhAPAOQAxATA1AAIgQAOIhYAMQgIgLgSgLQgBAAgCgCQgRgKgMgPQAPgUgFgHQAIgPgpgLIANgmIBBAhIAFAOACagcQgWAAgCAAIgLgFQgGgDgJgCACHB8IAAAXIAoAAIATgbIAZgzIgPAAIAAg6IgdAAIAZgUIgYgnIgfAAIAQgTIgxAAIgFAIIgXARACcgMQAKgQgKAAQgBAAgBAAQAEgBAEAAQAFAAgLARgACUAZQAAAAAAgCQgBgJgDgIQgBgCAAgBIANgPACuAmIgDgBIACgCIABADIAJAVIAAgRgACrAlIgXgMACMBAIAAAAQAMgMgEgbACHB8IAugIIAAgnIgZANIgQgaABnBVQASgJAPgKQACgBACgBABbBbQACgBACgBQAEgCAEgCIAgAQIAAAXIgZgKIAAALIgXAFQgCgGAAgJQAAgIADgFQADgEAAgHgACMBAIAfgbAkWguQgLA2gBAOQAGATAMALQAAAKgFAOQgBAMAVAOQATANAmAVQAlAUANAFQAPAGBjgdQBKgWA1gZAkWguIAZAmQAgAhAmALIAAAQAkCh8QgJAWgLA4AivhDIgfAVAizBtIAAAMAkQA0QAkAhAkAM");
	this.shape.setTransform(29.2,16.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FF0000","#000000"],[0,1],0.7,-2.2,0,0.7,-2.2,8).s().p("AgRAhQAOgVgFgHQAIgNgogLIANgmIA+AhIAGAPIgNAAQgDAfAQAOIgfAVQgPgKgMgOg");
	this.shape_1.setTransform(7.4,5.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["#FFFFFF","#000000"],[0,1],-0.1,0.5,0,-0.1,0.5,2.9).s().p("AgYAHQAAgHAEgDQACgFABgHIADgCIAIgEIAfARIAAAUIgZgKIAAAMIgSgBIgEAFQgCgGAAgJg");
	this.shape_2.setTransform(40.2,27.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],-4.7,17.7,4.7,-17.7).s().p("AhPCPQgNgFglgVQgmgVgTgMQgVgOABgMQAFgOAAgKQgMgMgGgSQABgNALg3IAZAlQAgAhAmAMIAAAQIAAgQQgmgMggghIgZglQALg4AJgXQApALgIAPQAFAHgPAVQAMAOARALIADACQASALAIALIBYgNIAQgOQg1AAgxgSQgPgPACghIANAAIBDgBQBSABAdgCQAOgBAYAaQASAUAIARIADAGQAFAEAHACIACAAIAJACIAGABIAFABQAJACAGADQAQASAIAUIABADQADAJABAHIAAACQAEAbgMALIAAAAIgEADQgPAJgSAJIgIAEIgEACQg1AZhMAWQhRAZgYAAIgHgBgAhsBnIAAgNgAiBBPQgkgNgjggIgBAAIABAAQAjAgAkANIAAAAg");
	this.shape_3.setTransform(22.1,18.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["#FFFFFF","#000000"],[0,1],2.2,-7.5,0,2.2,-7.5,18.7).s().p("AgOBsIAAgYIAsgIIAAgnIgaANIgOgaIAAAAIAdgZIgUgMIgBgCQgBgJgDgIIgBgDIALgRQALgRgFAAIgIABIgWAAIgLgFQgFgDgKgCIgEgBIgHgBIgJgCIAYgRIAEgIIAwAAIgOATIAcAAIAYAnIgZAXIAdAAIAAA3IAPAAIgZAzIgTAcgAATgBIADABIAJATIAAgRIgJgCIgBgDgAguhOQALAAAGgDIAGAAIgGAAQgGADgLAAg");
	this.shape_4.setTransform(44.4,20.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.rf(["#FFFFFF","#000000"],[0,1],2,9.1,0,2,9.1,20.8).s().p("AgPBrIAAgXIAsgHIAAgoIgYANIgPgaIABAAIAcgZIAEABIAIATIAAgRIgIgCIgCgDIgCACIgUgLIAAgDQgCgIgDgJIgBgDIALgRQALgRgFAAIgIABIgWAAIgLgFQgFgDgJgCQAJAAAIgDIAEAAIgEAAQgIADgJAAIgFgBIgGgBIgKgBIAXgSIAGgIIAuAAIgOATIAeAAIAYAnIgZAWIAcAAIAAA4IAPAAIgZAzIgSAbg");
	this.shape_5.setTransform(51.6,17.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,60.4,34.6);


(lib.kist_l = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AgohWQAKgEAmAEQAwgPACgjQgagfgygLQgtAIg3AlIgdCMQANArAqA2QAjAvAWAPQAjAYAggUQAYgPACgNQAmADAZgHQAIgCAQgJQAKgUgZgMQhjgbATgNQAcgGAlAGQAUgHADgVQAEgZgggPQgPgEghAIQghAHgRAIQAEgEAcgTQAVgQgCgFQAGAPAQgPQAUgbgggSIhDAPQgmAMgIAZQgIgMAAgNQAAgOAIgQQgKgQAHgPAhiAgQADAVAWAMAgwg4QgTgTgLAGAg1BVQgEAWAlAXAAyA3IgbAA");
	this.shape.setTransform(14.8,18);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],9.6,17.1,-8.8,-6.1).s().p("AgjCmQgWgPgjgvQgqg2gNgrIAdiMQA3glAtgIQAyALAaAfQgCAjgwAPQgmgEgKAEQgGgJAAgJQAAgHADgGQgDAGAAAHQAAAJAGAJQgIAQAAAOQAAANAIAMQAIgZAmgMIBDgPQAgASgUAbQgQAPgGgPQACAFgVAQIggAXQARgIAhgHQAhgIAPAEQAgAPgEAZQgDAVgUAHQglgGgcAGIgbAAIAbAAQgTANBjAbQAZAMgKAUQgQAJgIACQgZAHgmgDQgCANgYAPQgPAJgPAAQgRAAgUgNgAgUCCQghgUAAgVIAAgEIAAAEQAAAVAhAUgAhJBBQgWgMgDgVQADAVAWAMgAgwg4IgBgBIgBgBIgBgBIAAAAIAAgBIgBAAIgBgBQgKgIgHgBIgCAAIAAAAQgDAAgDABQADgBADAAIAAAAIACAAQAHABAKAIIABABIABAAIAAABIAAAAIABABIABABIABABIAAAAgAAyA3g");
	this.shape_1.setTransform(14.8,18);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,31.7,37.9);


(lib.head = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],65.2,-14.1,-29.1,-14.1).s().p("ABikOYAAAAgCACgDADYgEADgEAEgGAGYgGAGgGAHgHAJYgIAIgHAKgIAMYgHAMgIAMgHAPYgHAOgEARgEAQYgBAJgDAIgDAIYgDAJgDAIgDAIYgHARgJAQgJAQYgJAPgIAQgHARYgHARgFARgFARYgFAQgFAQgCAQYgCAQgCAPgBAOYgBAHAAAGAAAGYAAAHAAAGAAAGYAAALABAKABAIYABAIAAAGABAFYAAAEABACAAAAYAAABABABABAAYABAAAAgBABAAIAAAAYAAAAABgDABgEYACgEACgGADgHYACgIADgJADgLYABgFACgGABgGYACgGACgGACgGYAEgNAEgOADgPYADgPAFgQADgQYACgIABgJACgIYACgJACgIACgIYACgJACgJACgJYABgIACgJABgHYAEgSAFgRAHgRYAFgRAJgOAJgPYAKgNAKgOAIgNYAIgNAHgNAFgMYAGgMAGgLAEgKYAFgKAEgJACgIYADgHACgHACgEYABgEAAgCAAAAYABgCgBgBgBAAYgBAAgBAAAAAA");
	this.shape.setTransform(26.2,50.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],26.8,-17.9,-67.4,-17.9).s().p("AhelKYAAAAABADABAFYABAFABAHADAKYADAJADALAEANYAFAMAFAOAFAPYAGAPAGARAIAQYAIARAJARAJASYAKASAIATAFAVYAGAUAEAVAEAWYACAJAAAKACALYABALACAKACALYABAKADAKABALYABAKACAKABAKYADAUAEATADASYADASADARAEAQYACAIABAHACAIYABAHACAHABAGYADANACALADAKYACAJACAHABAFYACAFABADAAAAIAAAAYAAABABABABAAYABgBABAAAAgBYAAAAAAgDABgFYABgFAAgIACgJYABgKABgMAAgNYAAgHABgHAAgHYAAgIAAgIgBgIYgBgRgBgRgBgTYgCgTgFgUgEgUYgCgKgDgKgCgKYgCgLgEgKgDgKYgGgVgIgVgIgSYgJgUgIgUgHgVYgDgKgCgKgDgKYgDgLgCgKgDgKYgCgUgDgUgHgSYgGgSgIgQgHgPYgHgPgHgNgIgLYgHgLgGgKgGgIYgFgIgFgGgDgEYgEgEgBgCAAAAYgBgBgBAAgBABYgBAAAAABAAAB");
	this.shape_1.setTransform(64.6,54.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],52.4,-17.6,-41.9,-17.6).s().p("AAelTYAAAAgBADgCAFYgBAFgCAHgCAKYgEASgEAbgDAgYgCAQgBARAAATYABASAAATACAUYABAUAAAVgCAVYgCAVgEAVgEATYgEAVgGAVgEAUYgDAVgEAUgEAUYgCAKgBAJgBAKYgBAFgBAEAAAFYgBAFgBAEAAAFYgDASgCARgCAQYgBAQgBAPgBANYgBANAAALAAAKYAAAJAAAIAAAFYABAFAAADAAAAIAAAAYAAABABABABAAYABAAAAAAABgBYAAAAABgDACgEYACgFACgHAEgJYADgJAEgLAEgMYAEgNAEgOAFgQYAEgPACgRAEgSYABgFABgFABgEYABgFAAgFABgFYABgJABgKABgKYACgUACgVACgVYABgVAAgWAAgWYAAgTgBgWACgVYABgVAEgVAFgTYAEgUAGgUABgSYACgSAAgSAAgQYgBgggCgbgDgTYgBgJgCgIgBgFYgBgFAAgCAAAAYgBgCgBAAgBAAYAAAAgBABAAAA");
	this.shape_2.setTransform(39,54.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],37.4,-17.6,-56.8,-17.6).s().p("Agwk+YAAAAAAADgBAEYAAAFAAAHAAAJYABASACAaAEAeYADAPADAQAEARYAFARAFARAGASYAGASAFATADAUYACATAAAUAAAUYAAATAAAUAAAUYABAUABATABATYABATADASABARYABARACARADAPYACAPACANACAMYADANACAKACAJYADAJABAHACAEYABAFABADAAAAIAAAAYAAABABAAABAAYABAAABgBAAgBYAAAAAAgCABgFYABgFABgHABgJYACgIABgLABgNYABgMAAgOABgQYABgPAAgQAAgSYAAgRgDgTgDgTYgCgTgEgTgDgUYgDgUgFgTgFgSYgGgUgFgUgDgTYgEgUgBgUAAgTYAAgTAAgTgCgSYgBgRgEgQgEgOYgIgegJgYgHgQYgDgIgEgHgCgEYgCgFgBgCAAAAYgBgBgBAAgBAAYgBABAAAAAAAB");
	this.shape_3.setTransform(54,54.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],19.7,-4.3,-74.6,-4.3).s().p("AhaiHYAAAAAAACABADYABACABAEACAEYACAFADAFADAFYADAGADAGAFAGYAEAGAFAHAGAGYAGAGAIAGAIAGYAIAFAHAIAGAIYACAEADAFACAEYABAFABAFABAFYADAIADAKAFAKYAEAJADAJAEAJYAIARAKAPAJAMYAFAGAEAGAEAFYAFAFAEAEADAEYAEADACADACABYACACABABAAAAIABAAYAAABACAAABgBYAAgBAAAAAAgBYAAAAAAgBAAgDYAAgCAAgEAAgFYgBgFgBgGgBgGYgBgHgCgHgCgIYgCgHgDgIgEgJYgDgIgEgIgGgJYgGgIgGgIgGgIYgGgJgIgFgIgHYgIgIgHgHgGgJYgBgEgDgEgCgFYgCgFgCgEgCgFYgEgKgDgJgFgIYgFgIgGgGgGgFYgGgGgFgFgGgDYgFgEgFgCgFgDYgEgCgEgBgCgBYgDgBgBAAAAAAYgBgBgCABAAABYAAABAAAAAAAA");
	this.shape_4.setTransform(71.8,41.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],72,3.4,-22.3,3.4).s().p("ABWiMYAAAAgBABgDAAYgCABgEACgEACYgFACgFADgFADYgGAEgGAEgGAFYgGAGgGAGgFAIYgGAHgDAKgEAKYgCAFgCAEgCAFYgDAEgBAFgCAEYgGAJgIAHgIAHYgIAIgIAIgGAGYgHAJgFAJgFAIYgFAJgFAJgDAJYgDAIgCAJgCAIYgBAEgBAEgBADYAAAEAAAEgBADYAAAHAAAGAAAFYAAAEAAAEAAADYABADAAABAAAAYAAABABABABAAYABAAAAAAABgBIAAAAYAAAAABgBACgCYABgCADgDADgDYADgEAEgFADgFYAEgFADgHAFgGYAEgGAEgIAEgHYAEgIAFgIADgJYADgJAEgJAEgJYAEgJACgLADgIYAEgKADgKAEgIYAFgJAJgGAIgGYAIgGAIgGAGgFYAHgGAEgHAFgGYAEgHAEgFAEgGYADgGADgFACgEYACgFABgDABgDYABgDAAgBAAAAYABgBgBgBgBgBYgBAAAAAAgBAA");
	this.shape_5.setTransform(19.4,33.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1,1,1).p("ACRpSIAFABQC3AUB4FsQhYiliHhqQDLDEgKECQgFBhghBZQgOgUgHgMQANCKgQBtQgPBqgoA/QACgFgCADQgqkfhYiLQAcGLgXDEQgOjjggh9QgliShXh7QgRBhgmC6QgaClALCiQhJkUg0kaQgJgwgJgxQggAigHB+QgCAjAAAoQAAA6AECIQABCDgEBfQgHh4gwjgQgPhBgMg0QgRhIgIgwQgPhZAEhIQADgpAIglQgrAngzBtQgEAKgFAKQABgMAAgLQAIkQCXkCIhIAwQAKgLAJgOQA4hWAHgHQAkgZAhgQQAmgSAugNQAWAEAMAFQApgkBLgcIgNApQB2gWDDBrQhigXhJAKAhfqCIAGADQAPAIAFASAFsCAQhMiBAJh9ACmgfIAKCT");
	this.shape_6.setTransform(45.3,70.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.rf(["#996600","#E0AD12","#F9C519","#FFFFFF"],[0.239,0.478,0.671,0.945],-2.5,-41.7,0,-2.5,-41.7,81.6).s().p("ACHFjQgliThXh5Ig3EZQgaClALCkQhJkVg0kaIgShgQggAhgHB/QgCAiAAAoQABA6ADCJQACCBgEBhQgIh6gwjfIgbh1QgRhIgIgwQgPhZAEhIQADgpAIglQgrAngzBtIgJAUIABgXQAIkQCXkCIhIAwQAKgLAJgOQA4hWAHgGQAkgaAigQQAlgRAugOQAXAFALAEIAHADQAOAIAGASQgGgSgOgIIgHgDQAqgkBKgcIgMApQB1gWDDBrQhjgXhIAKQC3AUB4FtQhYimiIhqQDMDEgJECQgGBigiBYIgUghQANCMgPBsQgQBqgnA/QAAgCAAAAQAAgBAAAAQAAAAAAAAQAAAAgBABQgqkfhYiLQAcGLgXDEQgOjkggh8gAhoCxQBGlSAFlVQgFFVhGFSgAEXCrQgQlTiklEQCkFEAQFTgAB8CdQgKlIhLk2QBLE2AKFIgAFsB/QhEh0AAhuIABgbIgBAbQAABuBEB0gACwB0IgKiTgAkcBHQAZkeCqj8QiqD8gZEegAFiicQhQiyhkhiQBkBiBQCygAlYjoQAxifB+h5Qh+B5gxCfgACWpRIgFgBgAhfqCg");
	this.shape_7.setTransform(45.3,70.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,92.6,143.5);


(lib.hand_r = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AAwidQhZgihAg0QhEg4gghCQgKhuAghCQAeg/A7gHQA7gIA/AyQBHA2A6BrQDyFFjLE6QhQFQlmAuQhGgiAlhJQAxgDAsgsQAgggAqhFQBChuADgFQAog+AogcQgXgWAEh1QAGikAUgHQAcgKAZAKAApCZQAjAIAGARAApCZQBNAAAegl");
	this.shape.setTransform(28.9,61.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],43.7,-28.9,-39.8,19.3).s().p("AkTH6QAxgDAsgsQAgggAqhFIBFhzQAog+AogcQgXgWAEh1QAGikAUgHQAcgKAZAKQgZgKgcAKQhZgihAg0QhEg4gghCQgKhuAghCQAeg/A7gHQA7gIA/AyQBHA2A6BrQDyFFjLE6QhQFQlmAuQhGgiAlhJgAApCZQAjAIAGARQgGgRgjgIQBNAAAeglQgeAlhNAAIAAAAg");
	this.shape_1.setTransform(28.9,61.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,59.9,124.8);


(lib.hand_l = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ABygOQASANgBAOABygOQhFgsiDAgQiHAogmAAQgfABghgHQgqgIgYgOQgngFgNAtQgMAsATA0QA0BCA4gEQA0gDCLACQCNgDCDgcQASAUAeADQAcACAXgNQBZhcAyhFQAxg/AXg4QgFg/g/gFQjSAxg3B5gACfA2QgBAwgbAY");
	this.shape.setTransform(44.7,18.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000000","#A3602B","#FFFF99"],[0.004,0.333,0.945],4.8,17.9,-4.8,-17.9).s().p("AmyB6QgTg0AMgsQANgtAnAFQAYAOAqAIQAhAHAfgBQAmAACHgoQCDggBFAsQARAMAAANIAAACIAAgCQAAgNgRgMQA3h5DSgxQA/AFAFA/QgXA4gxA/QgyBFhZBcQgXANgcgCQgegDgSgUQiDAciNADQiLgCg0ADIgHABQg0AAgxg/gACDB+QAbgYABgwQgBAwgbAYg");
	this.shape_1.setTransform(44.7,18.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,91.5,39);


(lib.gitar = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().rs(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,10.2).ss(1,1,1).p("Ag2hPQAHBdBmBC");
	this.shape.setTransform(146.8,93.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().rs(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,10.9).ss(1,1,1).p("AhlgSQCBApBKgF");
	this.shape_1.setTransform(162.5,103.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().rs(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,54.6).ss(1,1,1).p("AkGkWQhfgHgjgjQgugDgOAjQgNAlAYBEQAGASAWAWQARARAjAeIB2A4QBVBcACBWQA+DRC3gdQG8hnhbmv");
	this.shape_2.setTransform(142.7,144.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().rs(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,3.3).ss(1,1,1).p("AAcAAQAAALgIAJQgJAIgLAAQgKAAgJgIQgIgJAAgLQAAgLAIgIQAJgJAKAAQALAAAJAJQAIAIAAALg");
	this.shape_3.setTransform(155.8,165.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().rs(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,4.5).ss(1,1,1).p("AAmAAQAAAPgLAMQgMALgPAAQgPAAgLgLQgMgMAAgPQAAgPAMgLQALgMAPAAQAPAAAMAMQALALAAAPg");
	this.shape_4.setTransform(143.4,160.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AhuiKYAAAAAAAGAAALYAAAFAAAHABAHYAAAIABAJABAJYACAJABAKAEAKYABAFACAFACAGYACAFADAFACAFYAEALAGAJAFALYAGAKAGALAHALYAGALAIAJAHAKYAJAIAJAJAJAHYADACACACABACYABABADACACABYAFADAFADAFADYAKAEAJAFAJACYAFABAEABAEACYAEAAAEABAEABYAIABAGABAGAAYAKAAAHAAAAAAYAAAAAAAAAAAAYAAAAAAAAAAgBYAAAAgGgBgLgCYgFgBgGgCgIgCYgDgBgEgBgEgBYgEgBgEgCgEgCYgJgCgIgFgJgFYgFgCgEgDgFgDYgCgBgDgBgCgCYgCgCgCgBgBgCYgJgGgIgIgJgIYgIgJgJgJgHgJYgIgKgGgKgGgLYgFgLgFgIgDgLYgCgGgCgFgBgGYgBgFgBgFgCgFYgCgKgCgKgCgJYgCgJgBgIgCgHYgBgHgBgHgBgFYgBgLgCgGAAAAYAAAAAAgBAAABYAAAAgBAAAAAA");
	this.shape_5.setTransform(167,201.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgqgoYAAAAAEAHAHAJYACACACACACACYADACADACADACYAGAEAFAFAFAFYAAADACADACADYADACACADADADYAEAFAFAEAFAEYAJAHAHADAAAAYAAAAABAAAAAAYAAAAAAgBAAAAYAAAAgEgHgHgJYgDgEgFgFgFgFYgDgCgDgCgCgDYgDgCgDgCgEAAYgEgFgGgFgDgGYgCgDgCgDgCgCYgDgDgCgCgCgBYgJgIgHgDAAAAYAAAAgBAAAAAAYAAAAAAABAAAA");
	this.shape_6.setTransform(156.6,138.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgzgxYAAAAAEAIAKALYACACACADADACYADADAEACADADYAIAFAGAGAGAFYAAAEADAEADADYADAEADADADADYAGAGAGAFAFAFYALAIAIAFAAAAYAAAAABAAAAAAYAAgBAAAAAAAAYAAAAgFgIgJgLYgEgFgFgGgHgFYgDgDgDgDgEgDYgDgDgEgDgEAAYgFgGgHgGgFgHYgCgEgDgDgCgDYgDgDgDgCgCgDYgGgEgEgDgEgDYgDgCgCgBAAAAYAAAAgBAAAAAAYAAABAAAAAAAA");
	this.shape_7.setTransform(150.6,143.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgzgxYAAAAAEAIAKALYACACACADADACYADADAEACADADYAIAFAGAGAGAFYAAAEADAEADADYADAEADADADADYAGAGAGAFAFAFYALAIAIAFAAAAYAAAAABAAAAAAYAAgBAAAAAAAAYAAAAgFgIgJgLYgEgFgFgGgHgFYgDgDgDgDgEgDYgDgDgEgDgEAAYgFgGgHgGgFgHYgCgEgDgDgCgDYgDgDgDgCgCgDYgGgEgEgDgEgDYgDgCgCgBAAAAYAAAAgBAAAAAAYAAABAAAAAAAA");
	this.shape_8.setTransform(153.1,140.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgGgGYgBADAAACABABYABAAABAAABAAYABAAABAAAAAAYABAAAAABAAABYgBABABABAAABYAAABAAABABABIAAAAYACAAABAAACgBYABAAAAAAAAgBYABgCAAgBgBgCIABABYgBgCgBAAgBAAYgBAAgBAAgBAAYgBAAgBAAAAgBYAAAAAAgBAAgBYAAgBAAgCAAAAYAAgBgCgBgDACYAAAAgBAAAAAA");
	this.shape_9.setTransform(151.2,133.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgzgxYAAAAABACACADYADAEADAEAFAFYACADADADADACYADADADACAEADYAHAEAGAHAGAFYAAAEADAEADADYADADADAEADADYAGAGAGAFAFAFYALAIAIAFAAAAYABAAAAAAAAAAYAAgBAAAAAAAAYAAAAgFgIgJgLYgEgFgFgGgHgGYgDgCgDgDgEgDYgDgDgEgDgDgBYgGgFgHgGgFgHYgCgEgDgDgCgDYgDgDgDgCgCgDYgKgJgJgEAAAAYgBAAAAAAAAABYAAAAAAAAAAAA");
	this.shape_10.setTransform(158.7,135.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgzgxYACADACAEADADIAAABIABACIACACIAEAEIAAAAYABABABABABABIADADYABACACABACACYAFADAEADAEADYAIAGAFAHAFAIYAHAIAGAHAIAHYAIAHAIAGAJAFYAAAAABAAAAAAYAAAAAAgBAAAAYgGgJgGgIgHgHYgHgIgHgGgIgHYgIgFgHgFgHgHYgDgEgDgFgDgEYgCgCgBgCgCgBIgFgFIgBgBIgEgEIgFgDYgDgDgDgCgEgCYAAAAgBAAAAAAYAAAAAAABAAAA");
	this.shape_11.setTransform(161,132.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().rs(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,4.5).ss(1,1,1).p("AAmAAQAAAPgLAMQgMALgPAAQgPAAgLgLQgMgMAAgPQAAgPAMgLQALgMAPAAQAPAAAMAMQALALAAAPg");
	this.shape_12.setTransform(138.2,150.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().rs(["#FFFFFF","#000000"],[0,1],0.3,0.1,0,0.3,0.1,2.7).ss(1,1,1).p("AgOATQgIgyAmAR");
	this.shape_13.setTransform(126.6,72.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().rs(["#FFFFFF","#000000"],[0,1],-1.2,-4.6,0,-1.2,-4.6,11.5).ss(1,1,1).p("Agph8QCFDChOA3");
	this.shape_14.setTransform(129.3,87.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(0.2,1,1).p("AoGoiIA4A7IBEBHIBEBIIBMBQIBEBHIBOBTIBRBUIA5A9IAxAzIAzA2IAmApIAtAvIAoApIAeAgIAkAnIDEDP");
	this.shape_15.setTransform(97.8,81);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(0.3,1,1).p("AniotIAkAmIBEBIIBEBHIBMBQIBEBIIBOBSIDuD7ICTCbIAmAmIBBA/IBLBKIA2A1IAKAKIAHAHAohoZIA2A5IBEBHIBEBIIBMBQIAhAjIAEAEIAfAgIBOBTIBRBUIA5A9IAxAzIAOAQIAHAHIAeAfIAmApIAOAOIAIAIIAXAZIAoApIAcAeIAlAnIC4DDIAMAMIACADIADAD");
	this.shape_16.setTransform(102.9,78.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgjAlIBQhKIAAAAIhXBCYgCACAAADABACYACADADAAACgCYABAAAAAAAAAA");
	this.shape_17.setTransform(124.8,106.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgjAlIBQhKIAAAAIhXBCYgCACAAADABACYACADADAAACgCYABAAAAAAAAAA");
	this.shape_18.setTransform(121.1,102.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgjAlIBQhKIAAAAIhXBCYgCACAAADABACYACADADAAACgCYABAAAAAAAAAA");
	this.shape_19.setTransform(117,97.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgjAlYAAAAAUgTATgSYAKgJAKgJAIgHYAHgIAFgEAAAAIAAAAYAAAAgFAEgIAGYgIAHgLAJgLAIYgVAPgWARAAAAYgCACAAADACACYABADADAAADgCYAAAAAAAAAAAA");
	this.shape_20.setTransform(113.4,93.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgjAlIBPhKIAAAAIhWBCYgCACAAADACACYABADADAAADgCYAAAAAAAAAAAA");
	this.shape_21.setTransform(107.6,88.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgjAlIBQhKIAAAAIhXBCYgCACAAADABACYACADADAAACgCYABAAAAAAAAAA");
	this.shape_22.setTransform(102.8,83.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgjAlIBQhKIAAAAIhXBDYgCABAAADABADYACACADAAACgCYAAAAABAAAAAA");
	this.shape_23.setTransform(97.1,76.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgjAlIBQhLIAAAAIhXBEYgCABAAADABADYACACADAAACgBYAAgBAAAAABAA");
	this.shape_24.setTransform(89.4,68.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgjAlYAAAAAUgTATgSYAUgSAVgTAAAAIAAAAYAAAAgWARgWARYgVAPgWARAAAAYgCACAAADABACYACADADAAACgCYABAAAAAAAAAA");
	this.shape_25.setTransform(82.1,59.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgjAlIBQhKIAAAAIhXBCYgCACAAADABACYACADADAAACgCYABAAAAAAAAAA");
	this.shape_26.setTransform(75.5,52);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgjAlIBQhKIAAAAIhXBCIAAAAYgCACAAADABACYACADADAAACgCYABAAAAAAAAAA");
	this.shape_27.setTransform(68.2,43.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgjAlIBQhKIAAAAIhXBCYgCACAAADABACYACADADAAACgCYABAAAAAAAAAAIAAAA");
	this.shape_28.setTransform(61.5,36.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgkAmIBRhMIAAAAIhXBEYgCACgBADACACYACACADABACgCYAAAAAAAAAAAA");
	this.shape_29.setTransform(54.8,29.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#000000").ss(0.4,1,1).p("AodowIAYAZIBRBTIBEBIIBEBIIBMBPIAhAjIAJAKIAZAbIBPBSIAeAgIAKAKIAmApIA8A/IAwAzIARASIAIAIIAbAcIAmAoIARASIAHAHIAVAXIAnApIAcAbIAmAmIBAA/IBMBKIA2A2");
	this.shape_30.setTransform(99.3,74);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#000000").ss(1,1,1).p("AvKtdQAKgQAWgLQAbgPAkgBQCHgEBUAKQCAAQBnA1QAGADgFAMQgDAHgLATQgPAjATAcAoYqTQARgaAXgQQAbgTAjgFQAEAGAFAFIK6LlAoYqTQAHAIBDBKQBTBdCxDGQArAwArAvQAnAsAnAsQAcAgAbAgQAXAaAYAZQAXAaAYAaIB+CYIAVAaIAjglIAUgUIASgTIAXgYIARgSIgjgjIg/g+AvKtdIBBBDQBRAJCPBNQB8BCAuAqQBQBYDIDaQC3DMCGCnIBNBuIgoAqQhHgHgngoQgygDgPAoQgPApAbBNQAHATAZAZQAQAUAoAhICFA/QBgBqABBgQBGDsDQghQH0h0hnnnQhIjGi5gTQhKAIhUgzQg8hIgrhnQgRgpgIgMQgNgVgTgFQhVgWgqAdQgmAaAWAgQBbCAg1AxAvKtdQCbApBLAfQB9AzBPBPAHvI1IAogoIAagZIAbgcIAcgbIAWgXIAygyIBgBgIjBDBgAGTG+IAngnIhKhKIgnAmIhAg/IBBhAIAUgVIAUgUIAXgXIAVgVIA/BAIgUAUIgXAXIgDADIBLBKIADgDIAXgXIAUgUIA/BAIgTATIAAABIgXAWIgbAbIAAABIgVAUIgHAHIgZAaIgaAZgADAEEQAogJAFgj");
	this.shape_31.setTransform(97.1,90.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,4.4).s().p("AgBAnIgEgBQgEgBgDgDQgFgEgBgHIgBgIIAAgdIABgKQACgGAGgEQAFgEAFABIAAgBQALABAFAHQADAEABAOIAAAYQAAAMgDAFQgCAFgGADQgEACgFAAIgBAAg");
	this.shape_32.setTransform(156.6,184);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,2.9).s().p("AgTAUQgIgIAAgMQAAgKAIgJQAJgJAKABQALgBAJAJQAIAJAAAKQAAAMgIAIQgJAIgLAAQgKAAgJgIg");
	this.shape_33.setTransform(155.8,165.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,4).s().p("AgaAbQgLgLAAgQQAAgOALgMQAMgMAOAAQAPAAAMAMQAMAMAAAOQAAAQgMALQgMAMgPAAQgOAAgMgMg");
	this.shape_34.setTransform(143.4,160.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,4).s().p("AgaAbQgMgLABgQQgBgOAMgMQAMgMAOAAQAQAAALAMQALAMAAAOQAAAQgLALQgLAMgQAAQgOAAgMgMg");
	this.shape_35.setTransform(138.2,150.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.lf(["#B13A3A","#990000","#000000"],[0.349,0.663,1],-26.8,-15.4,10.3,6).s().p("AgjBvIAlgmIhJhJIgnAlIhAg+IBBhAIDBDNIjBjNIAUgVIC2DBIAMAMIgMgMIi2jBIAUgUIBAA/IhAg/IAXgWIA+A/Ig+g/IAVgWIA+BAIgVAVIgVAWIgCADIBIBJIADgEIA3A2Ig3g2IAXgUIA2AzIAKAKIgKgKIg2gzIAUgUIA/A9IgTAUIAAAAIgKgKIAKAKIgXAWIgJgJIAJAJIgbAbIAAABIgMgNIAMANIgVAUIgHAHIgLgLIALALIgZAaIgLgLIALALIgaAZgACbAugABEAFgABbgPgAhthZgAhZhugAhFiCgAguiYg");
	this.shape_36.setTransform(141.2,124.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.lf(["#FFFFFF","#000000"],[0,1],-14.4,0,14.4,0).s().p("AiPAwIAogoIAagXIAbgcIAcgbIAWgXIAwgyIBgBgIi/C/gAg0A6IgzgygAgbAgIgygvgAgBADIgxgugAAcgTIgygzgAAygqIgygzg");
	this.shape_37.setTransform(161.1,142.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,3.8).s().p("AgZAHQgLgCAAgFQAAgEALgDQALgDAOAAQAPAAALADQALADAAAEQAAAFgLACQgLAEgPAAQgOAAgLgEg");
	this.shape_38.setTransform(12.3,3.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,3.8).s().p("AgZAHQgLgCAAgFQAAgEALgDQALgDAOAAQAPAAALADQALADAAAEQAAAFgLACQgLAEgPAAQgOAAgLgEg");
	this.shape_39.setTransform(21.3,3.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,3.8).s().p("AgZAHQgLgCAAgFQAAgEALgDQALgDAOAAQAPAAALADQALADAAAEQAAAFgLACQgLAEgPAAQgOAAgLgEg");
	this.shape_40.setTransform(30.5,4.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,3.8).s().p("AgZAIQgLgDAAgFQAAgDALgEQALgDAOAAQAPAAALADQALAEAAADQAAAFgLADQgLADgPAAQgOAAgLgDg");
	this.shape_41.setTransform(38,6.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,2.1).s().p("AgRAKQgBgCAEgFIACgBIAIAIIgIgIQAEgDAGgDQAFgEAFgCIAHAIIgHgIIACAAQAGgCABADQACADgEAEQgFADgHAEIgHAFIgFABIgEABQAAAAgBgBQgBAAAAAAQgBAAAAAAQAAgBgBAAgAgMACgAAIgKg");
	this.shape_42.setTransform(120,98.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,2.1).s().p("AgRAKQgBgDAEgEIAIAHIgIgHQAFgDAHgFIAHgEIAIAJIgIgJIAFgBQAGgBABACQACADgEAEIgCACQgEACgGADQgEAEgFABIgDABIgEABQAAAAgBgBQgBAAAAAAQgBAAAAAAQAAgBgBAAgAgOADgAAFgJg");
	this.shape_43.setTransform(111.2,89.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,2.1).s().p("AgRAKQgBgCAEgFQAFgDAHgEIACgBIAIAIIgIgIQAFgEAFgBQAGgBABACQACACgEAFIgHAFIgFACQgGAFgGABIgEABQAAAAgBgBQgBAAAAAAQgBAAAAAAQAAgBgBAAgAAAgFg");
	this.shape_44.setTransform(94.5,70.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,2.1).s().p("AgNAMQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAIAAgCIAEAEIgEgEIADgFQAFgDAHgEIACgCIAJAHIgJgHQAFgDAFgBQAGgBABACQACADgEAEIgGADIgGAFQgGAEgGABIgDABIgBAAgAgRAIgAAAgGg");
	this.shape_45.setTransform(80,55.3);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.lf(["#FFFFCC","#330000","#990000","#491502","#DAA186","#330000"],[0,0.494,0.631,0.749,0.945,1],-66.1,0,66.1,0).s().p("AEWKmQgBhhhghqIiFg+QgogigQgTQgZgZgHgUQgbhNAPgpQAPgoAyADQAnAoBHAIIAogrIhNhuQiGimi3jMIkYkyQgugrh8hCQiPhMhRgJIhBhEQCbApBLAfQB9A0BPBPIBKBRIEEEjIBWBgIBOBXIA3BAIAvA1IAvAzIB+CXIAVAaIAjglIAlAnIglgnIAUgUIAlAnIglgnIASgTIAnAmIgngmIAXgYIAnAnIgngnIARgRIgjgjQAcgUAAgnQAAhChWh7IAAgFIAAAAQgFgiAVgBIAAAAIAAAAQAHABAKAEQgKgEgHgBIAAAAIAAAAQgVABAFAiIAAAAIAAAFQBWB7AABCQAAAngcAUIg/g/QA1gxhbiAQgWgfAmgaQAqgdBVAVQATAFANAVQAIANARApQArBmA8BJQBUAyBKgIQC5ATBIDHQBnHmn0B0QgaAEgXAAQioAAg9jOgAH1NIQAVAAAWgEQFxhVAAk5QAAhAgPhJQAPBJAABAQAAE5lxBVQgWAEgVAAIAAAAIAAAAQiVgBg2i1IgBgCQgBhWhVheIh2g3QgkgegQgSQgWgWgGgRQgOgtAAgfQAAgRADgMQAMghAoAAIABAAIAAAAIAHAAQAiAkBgAGQAogJAFgjQgFAjgoAJQhggGgigkIgHAAIAAAAIgBAAQgoAAgMAhQgDAMAAARQAAAfAOAtQAGARAWAWQAQASAkAeIB2A3QBVBeABBWIABACQA2C1CVABIAAAAIAAAAgAI2LDQgJAJAAAMQAAAMAJAIQAIAJAMAAQAMAAAJgJQAIgIAAgMQAAgMgIgJQgJgIgMAAQgMAAgIAIgAGzKLQgMAMAAAQQAAAQAMALQALAMAQAAQAQAAAMgMQALgLAAgQQAAgQgLgMQgMgLgQAAQgQAAgLALgAHvIgIBgBfIDBjBIhghfIgyAyIghghIgCgCIgHgHIAHAHIACACIAhAhIgWAWIgrgqIArAqIgcAcIgkglIAkAlIgbAbIgrgqIArAqIgaAaIgqgqIAqAqgAF+InQgLAMAAAQQAAAQALALQAMAMAQAAQAQAAALgMQAMgLAAgQQAAgQgMgMQgLgLgQAAQgQAAgMALgAG6GCIgnAmIBABAIAagaIAZgaIAHgHIAVgUIAAAAIACACIAEADIgEgDIgCgCIAbgcIAXgWIAAAAIAHAHIgHgHIATgUIg/g/IgUAUIgXAWIgDAEIhLhLIADgCIBLBJIhLhJIAXgXIBLBKIhLhKIAUgVIg/g/IgVAVIgXAXIgUAUIgUAUIhBBAIBABAIAngngAIkGbIgCgCgALkB5IAOgBIAAAAIACAAIgCAAIAAAAIgOABIAAAAIgBAAQg+gBhegcIgBAAIgQgFIgNgEIgCAAQhnhCgHhcQAHBcBnBCIACAAIANAEIAQAFIABAAQBeAcA+ABIABAAIAAAAgAIiGZgAJ+GRgAJUFngAGyD1gAHJDegAElC3gAE5CjgAFLCQgAFiB4g");
	this.shape_46.setTransform(97.1,92.8);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.lf(["#000000","#CC6600","#FFFFCC","#AF7440","#1B1007"],[0.004,0.298,0.514,0.702,0.988],84.7,5.9,-65.3,5.9).s().p("AFAHKIh+iYIgvg0IAagWIAyA2IgSAPIASgPIAnAoIgVASIAVgSIAtAwIgYAVIAYgVIAnApIgaAWIAagWIAeAgIgiAlgAFaGfIAWgSIAcAeIgUAUgAFwGNIATgQIAcAbIgTATgAFaGfIgngpIAWgTIAnAqIgWASgAGDF9IASgQIgSAQIgngqIATgRIgTARIgVgWQADgFgBgCQgBgDgHACIgCAAQgFACgGADQgGAEgEAEIgCACQgEAEABADQABACAHgBIAFgCIAXAZIgWATIgtgwIAWgSIAOAOIgOgOIASgQIARARIgRgRIAZgVIgZAVIgmgpIAagWIgaAWIgagcIABgBQAEgFgCgCQgBgDgGACIgFABIgJAEQgHAFgEAFQgFAEABADQACACAGgBIADgBIAdAfIgWATIgyg2IAVgTIAPAQIgPgQIATgQIAQASIgQgSIATgQIgTAQIgxgzIAVgSIgVASIg7g+IAXgUIgXAUIgpgrIAIgHQADgEgBgDQgCgCgGABQgFABgGAEIgCABQgIAEgEAFQgFAFACACQACADAGgCQAGgBAHgEIAFgDIApArIgTAQIhRhVIATgPIAfAfIgfgfIAagWIgaAWIhMhSIAagWIBMBSIDwD7ICTCbIgWAYgAFwGNIgngqIATgQIAnAqIgTAQgAG1GAgAEiDlIjwj7IhMhSIAGgFIgGAFIhEhIIAIgGIgIAGIhLhPIAKgJIgKAJIhFhIIALgKIgLAKIhDhIIAMgKIgMAKIglgmIAlAmIgaAXIhRhUIBRBUIgTAQIg2g5IA2A5IgWASIg4g7IA4A7IgHAGIhKhRQARgaAYgRQAagSAjgFIAJALIK6LlIA/A+IAjAjIgRASgAGDF9gAFJFjIgXgZIAJgEQAHgEAFgFIAVAWIgTAQgAFcFTgAEyFKgAEGFGIgngoIAWgTIAnApIgWASgAFHE9gAEcE0IgngpIATgQIAmApIgSAQgAEuEkgAD1ELIgdgfQAFgBAGgEQAGgEAFgEIAaAcIgTAQgACTD+Igvg1IAYgUIAxAzIgaAWIAAAAgAEID7gADYDsgACtDoIgxgzIAWgTIAwAzIgVATgADuDfgADCDVIgwgzIASgQIAxAzIgTAQgABkDJIg5hAIAVgTIA8A/IgYAUIAAAAgADVDFgAB8C1Ig8g/IAWgSIA8A+IgWATgACSCiIg8g+IATgQIA7A+IgSAQgACkCSgAArCJIhMhYIATgQIBOBVIgVATIAAAAgABAB2IhOhVIATgSIBRBVIgWASgABpBUgAghAxIhWhdIkEkkIAHgGIBEBHIgHAHIAHgHIBEBIIgIAHIAIgHIBMBQIgMAKIAMgKIBDBIIgMAKIAMgKIBPBQIgTAQIAAAAgABAApgAgOAhIhPhQIAWgTIBMBRIgTASgAAFAPIhMhRIATgQIBMBSIgTAPgAAYAAgAhdgvIhDhIIAVgSIAiAjIgigjIATgQIAiAjIgigjIAagXIBEBIIgaAWIgZgbIAFgFQAFgEgCgDQgCgCgFABQgFABgFADIgEACQgIAEgEAFIgDAFIAAACQAAABABAAQAAAAAAAAQABABAAAAQABAAAAAAIAfAgIgWATgAhHhCIgfggIAFgBQAGgBAHgEIAHgFIAZAbIgTAQgAhmhiIAAAAgAgahogAhNhtgAigh3IhMhQIAWgSIBLBQIgVASgAiLiJIhLhQIATgQIBLBQIgTAQgAh4iZIhLhQIAagWIBLBPIgaAXgAheiwgAjsjHIhEhIIAVgSIBFBIIgWASgAjWjZIhFhIIATgQIBFBIIgTAQgAjDjpIhFhIIAagWIBFBIIgaAWgAipj/gAkwkPIhEhHIAWgSIBDBHIgVASgAkbkhgAleloIATgQIBDBHIgTAQgAkIkxIhDhHIAagXIBDBIIgaAWgAjulHgAl0lWgAlelogAkxmPg");
	this.shape_47.setTransform(88.8,66.5);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.rf(["#FFFFFF","#000000"],[0,1],0,0,0,0,0,3.8).s().p("AgZAHQgLgCAAgFQAAgEALgDQALgDAOAAQAPAAALADQALADAAAEQAAAFgLACQgLAEgPAAQgOAAgLgEg");
	this.shape_48.setTransform(47.1,9.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.lf(["#FFFFCC","#330000","#990000","#DAA186","#330000"],[0,0.494,0.631,0.945,1],-59.5,14.2,17.7,14.2).s().p("AgrgGQhLgfibgpQAKgQAWgLQAbgOAkgBQCHgFBSALQCAAQBnA1QAGADgFALIgOAaQgPAhATAdQgjAEgbATIgYgZIAYAZQgXAQgRAbQhPhPh7gygACqgnQgLADAAAFQAAAFALADQALAEAPAAQAQAAALgEQALgDAAgFQAAgFgLgDQgLgDgQAAQgPAAgLADgABPg+QgLADAAAFQAAAFALADQALAEAPAAQAQAAALgEQALgDAAgFQAAgFgLgDQgLgDgQAAQgPAAgLADgAAEhVQgJADAAAFQAAAFAJADQALAEAPAAQAQAAALgEQALgDAAgFQAAgFgLgDQgLgDgQAAQgPAAgLADgAhXhiQgLAEAAAFQAAAFALADQALADAQAAQAPAAALgDQALgDAAgFQAAgFgLgEQgLgDgPAAQgQAAgLADgAixhiQgLAEAAAFQAAAFALADQALADAQAAQAPAAALgDQALgDAAgFQAAgFgLgEQgLgDgPAAQgQAAgLADgADHBQg");
	this.shape_49.setTransform(27.4,12.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,196.3,216.9);


(lib.foot_r = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("Ag2AHYAAAAABAAADgCYABgBACAAACgBYACgBADAAACgBYADgBADAAADAAYADAAADAAADAAYADAAAEAAADAAYAEAAADAAADAAYACAAAEABADAAYAEABADABADAAYAHACAGAAAFABYALACAIgBAAAAYAAAAAAAAAAAAYAAAAAAgBAAAAYAAAAgGgEgLgCYgFgCgGgBgHgCYgDAAgEgBgEAAYgDAAgEAAgDAAYgCAAgEAAgEAAYgDAAgEAAgDABYgEAAgDABgDABYgDAAgDABgDABYgDABgCAAgCAAYgCACgCABgBABYgCABgCABAAAAYAAABAAAAAAAAYAAAAAAAAABAA");
	this.shape.setTransform(45.2,74.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCCCCC").s().p("AhGhhYAAAAABgBACAAYACgBADAAADABYAGABAJAGAIAJYAQARAQAcAOAcYAHAMAHAOAHANYAHAOAGAMAGAKYAMAVAIAOAAAAYAAAAABAAAAAAYAAAAAAAAAAAAYAAAAgEgQgKgWYgEgLgGgNgHgNYgHgOgIgMgIgNYgRgcgQgbgSgRYgJgIgJgGgHgBYgDgBgDABgCABYgCAAgBABAAAAYAAAAAAAAAAAAYAAABAAAAAAAA");
	this.shape_1.setTransform(28.2,32.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCCCC").s().p("ABAgfYgLABgMABgMABYgMABgLABgKADYgGABgGABgGACYgGACgFABgGAEYgCAAgBABgBABYgCACgBABgBABYgCACgBACAAACYgBAAAAACAAADYABAEADADACACYACADADACADACIABgIYgFADgFACgFADYgEADgFADgEAEYAAAAAAAAAAAAYAAABABAAAAAAYAFgCAFgCAFgCYAFgBAFgCAFgCYACgBABgCgBgCYAAgBAAAAAAgBIgBAAYgCgCgCgCgCgCYgBgCgBgCAAgBYgBgBAAgBABAAYAAgBAAAAABAAYAAAAABgBABgBYABgBABAAABgBYACgCACgBADgBYACgBADgBADgBYAFgCAGgCAFgBYAVgGAXgEAYgEYAAAAAAAAAAAAYAAAAAAgBgBAA");
	this.shape_2.setTransform(36.9,59.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("AkWkQQgCgDgVgfQgPgVgEgRQgGgbANghQANggAZgTQA+gxA6BPQAEAGAAAKQAAAFABALQAGAoAGApAj9lSQAKAOAZAAAiWmJQAmgiABBQQAwgQgIBlQA8BNA9A/QAEADBMBHQAqAnAXBtQgagRg2gpQghgagagRIgngdQgIgGgHgEQgUgVgPgeQgQggABgaAj0i0QBTClAQCaQgpCwASBCQAhAvAdgJIAoAAQgZgoANgnQAiAlAdAIQC4AVBihaAiKBtQgEAPgDAPAkWkQIAAAyQgCATAjAWIABABQAMAGBZAyQAhASAXA4QAQAoASBRAhCC9QgKgaA8g0AgSCWQgaAPgWAYQhGA/ASB6ADTC3QgCgcgwgdQhYgPhAAZAkWlCIAAAyAhvlbIAABnAEiFTQgFgbgSAEQgMghgZgWQAAAAAAgBQgbgYgpgJQgFAAgFgBAhOFUQgKgRAKgbQA0hBA7goQBvgLAIAuQhmgNg0A9AhCGjQAXAfBGAVQE0AZgtidQBhhTjAicADmEEQAegZhegn");
	this.shape_3.setTransform(32.3,47.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#000000","#58322C","#FFFFFF"],[0.161,0.502,0.945],-17.6,0,17.6,0).s().p("AhqBfQgegHgigmQgJgQAJgbQA0g/A+goQBsgMAJAuIAKACQAoAJAbAYIABAAQAYAWANAgQhQBIiIAAQgfAAgjgEgABdgLQhQgYgeAYQAQgMAaAAQAcAAAoAMgAhegOIACgBQAsgxBKAAIABAAIAAAAQAPAAAQACIADAAIgDAAQgQgCgPAAIAAAAIgBAAQhKAAgsAxIgCABg");
	this.shape_4.setTransform(41.5,76.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#000000","#56626F","#FFFFFF"],[0.161,0.502,0.945],5,8.3,0,-4.2).s().p("AhNBMQhIgWgXgfQgZglANgoQAhAmAeAHQC4ATBihXQASgFAFAbQAnCGjfAAQgjAAgqgDg");
	this.shape_5.setTransform(42.9,87.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#000000","#56626F","#FFFFFF"],[0.161,0.502,0.945],-32.3,0,32.3,0).s().p("AioGZQgShDApiwIAHgeIgHAeQgQibhTikIBlA4QAhATAXA3QAQAmASBUQgShUgQgmQgXg3ghgTIhlg4IgBAAQgjgXACgSIAAgyIgXgiQgPgVgEgSQgGgbANggQANggAZgUQA+gxA6BQQAEAFAAAKIABARQAmgjABBRQAwgRgIBmQA8BMA9A/IBQBKQAqAlAXBvQgagRg2gpIg7gtIgngaIgPgLQgUgUgPgfQgPgeAAgZIAAgDIAAADQAAAZAPAeQAPAfAUAUIAPALIAnAaIA7AtQA2ApAaARQDACchhBTQgFgbgSAFQgMgigZgWIAAAAQAHgHAAgHQAAgVhHgdQBHAdAAAVQAAAHgHAHQgbgYgpgJIgKgCQgIguhvAMQg7Aog0BBQgKAaAKARQgNAoAZAnIgoAAIgJACQgZAAgcgngAh2GRQgEgZAAgWQAAhYA4gyIgBgIQAAgZAzgtQgzAtAAAZIABAIQg4AyAABYQAAAWAEAZgAhCDYQAWgYAagPQgaAPgWAYgAChCaQAwAcACAcQgCgcgwgcIgKgCQgdgEgZAAIgBAAIAAAAQgtAAglANIgFACIAFgCQAlgNAtAAIAAAAIABAAQAZAAAdAEIAKACgAgSCxQAOgIANgGQgJgIAAgHQgBgXBvgLQhvALABAXQAAAHAJAIQgNAGgOAIgAAegQIgBgDIgBgBIgFgLIgCgFIgBgCIgEgIQhNikgngIIgDgBIgBAAQgDABgDABIgBAAIABAAQADgBADgBIABAAIADABQAnAIBNCkIAEAIIABACIACAFIAFALIABABIABADIAAAAgAhvjZIAAhmgAkWj0IAAgygAiKkcIgMhRIAMBRgAjakpQgZAAgKgNQAKANAZAAgAj0iZIAAAAg");
	this.shape_6.setTransform(32.3,44.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,66.6,97.1);


(lib.foot_l = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AB5BLYAAAAgOgMgVgRYgKgIgNgKgNgKYgOgKgOgJgPgJYgNgLgPgKgPgIYgHgFgHgDgHgEYgHgDgHgDgGgDYgGgCgGgDgFgCYgFgBgFgCgEgBYgHgCgFgBAAAAYAAgBAAABAAAAYAAAAAAAAAAAAYAAAAAEADAHADYADACAFACAFADYAEACAGADAGADYAGADAGAEAGAEYAHAEAHAEAHAEYAHAEAIAEAIAFYAHAEAIAFAFAEYAQAIAOAKAOAJYAOAKANAIALAIYAWAQAOAKAAAAYABABAAAAAAgBYAAAAAAAAAAAA");
	this.shape.setTransform(42.3,123.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCCCCC").s().p("AAqCCYAAAAgCgEgEgGYgBgEgDgEgCgEYgDgFgDgFgDgGYgDgGgDgGgDgHYgDgHgDgHgDgHYgDgIgBgIgDgIYgCgIgDgIgCgIYgDgGgCgJgCgIYgCgIgBgJgCgHYgCgIgCgIgBgHYgBgHgCgHgBgHYgCgGAAgGgBgFYgBgFgBgFgBgEYgCgHAAgEAAAAYgBgBAAAAAAAAYAAAAAAABAAAAYAAAAgBAEABAIYAAAEAAAEAAAGYAAAFAAAGABAGYABAHABAHABAHYAAAIACAIACAIYACAIACAIACAIYADAJACAIADAGYACAJAEAIADAIYADAIADAIAEAHYABAHAEAIADAGYADAHAEAGADAGYADAGADAFADAEYADAFADADACAEYAEAGADADAAAAYAAABAAAAAAAAYABgBAAAAgBAA");
	this.shape_1.setTransform(51.4,110.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCCCC").s().p("AgOBhYAAAAABAAABgBYABAAABgBABAAYAAgBABgBACgBYABgBABgBABgBYABgCABgBABgCYAAgDABgEACgFYACgEABgFABgGYACgFABgGABgGYABgMABgMABgNYABgLABgMAAgMYgBgMgBgLgBgKYgCgSgDgNAAAAYAAAAAAAAgBAAYAAAAAAAAAAAAYAAAAAAADgBAGYAAAGAAAHgBAKYAAAJAAALAAAMYAAAMABAMAAALYAAAMAAANgBAMYgBAFAAAGgBAFYgBAGgBAEgBAFYAAAEgBAFgCADYAAACgBABgBABYgBACgBABgBABYgBABAAABgBABYgBAAgBABAAAAYgCABAAAAAAAAYgBAAAAABABAAYAAAAAAAAAAAA");
	this.shape_2.setTransform(52.9,81.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCCCCC").s().p("AhaixYAAAAAFAFAHAIYACACACACACADYACADACACADAEYAEAGAGAHAFAHYAGAIAFAJAGAJYAHAJAGAKAGAKYAGAKAHAKAFALYAGAKAHALAFAMYAGAJAGALAFALYACAGADAGACAFYADAGACAFACAGYAFALADALAEAKYAEAKACAKADAJYADAJACAIACAIYACAHACAHABAFYACALACAGAAAAYAAABAAAAAAAAYABAAAAgBAAAAYAAAAgBgGgBgLYAAgGgBgHgBgHYgCgIgBgJgCgJYgCgJgCgLgEgKYgDgLgEgLgEgLYgDgFgCgGgCgGYgDgFgDgGgDgGYgFgLgHgJgGgLYgGgMgHgKgHgLYgHgKgEgLgHgKYgHgJgGgKgHgJYgGgJgGgIgGgIYgGgHgFgHgFgGYgDgDgCgDgCgDYgCgCgDgCgCgCYgHgIgFgFAAAAYAAAAAAAAgBAAYAAABAAAAAAAA");
	this.shape_3.setTransform(184.3,43.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,1,1).p("An8hxQgdgzAJhFQAGgdAuABQCbiPAnghQBvhgBmg8IC6hkQAdgGAVgnQAmgMDVAoQDYApApAcQAsAeAvA4QAhAmA2BMQBMBmBPIEQgfCOhnhUQhskBhlheQhohXhWh9Qhbi0iiAjALfh0QAWBvAZAFAlgJKQAHgPAEgKQAFgSgHgNQgthSAOiDQAWhRAQhoQATiGgJhYQAFgLATgRQAYgVAggQQBVgsCKhgQCDhdBhhQQAJgDAIgCQh7geh2ClAvnKBQADAiAcAHQEtgDEAghQich3iSgzQghAYgJAiQBQAUBIgDAvnKBQgQAaAQAiQAXAgARACQBmAMCtgIQBigFC7gNQAnAUAjgnQAOghgOghIgbgyQhoiDguiVAn+CbQAmiMgkiAAsMIZQgVgoAVgkQAGgiAOgUQARgXAYACQAEABAHAEIAYgZQAsgZARgnAsMIZQgRAGgDAQQgiAJAEAXQA1AHACAQArzIWQgPAAgKADAsgIvQBCAVAZAAAqsFuICwnfArEGHQBkAtCdB2AmPLRQAsglg4gmAs+JPIipAy");
	this.shape_4.setTransform(100.9,74.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#000000","#56626F","#FFFFFF"],[0.161,0.502,0.945],-1,7.3,-1.8,-1.7).s().p("AkIArQgRgCgXggQgQggAQgaQADAiAcAHQErgDEAghQA4AmgsAjQi7ANhiAFQhEADg7AAQhWAAg8gHg");
	this.shape_5.setTransform(31.4,143.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#000000","#58322C","#FFFFFF"],[0.161,0.502,0.945],7.7,17.4,-7.7,-17.5).s().p("AkkA+ICogzQA2AHABAQQgBgQg2gHQgDgUAhgKQAEgQARgGQAKgDAOAAIACABQBCARA+AAIAAAAIABAAIAUAAIgUAAIgBAAIAAAAQg+AAhCgRIgCgBQAKgiAhgXQCQAzCbB0Qj/AikrACQgdgHgCghgAgDAAIAAAAIABAAIgBAAIAAAAIAAAAIgHAAIgCAAIgBAAIgWgCIAAAAIgTgFIgEgBIAAAAIgCgBIgFgBIgFgCIAAAAIgNgEIgDgBIgCAAIgEgBIgCgBIACABIAEABIACAAIADABIANAEIAAAAIAFACIAFABIACABIAAAAIAEABIATAFIAAAAIAWACIABAAIACAAIAHAAIAAAAg");
	this.shape_6.setTransform(30.2,132.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#000000","#56626F","#FFFFFF"],[0.161,0.502,0.945],128.2,-17.6,-130.6,17.7).s().p("An7LYQArglg4gmQibh2iSg0QghAYgKAiQgOAAgKADQgVgoAVgkQAFgiAPgUQARgXAYACQAEABAHAEIAYgZQArgZASgnQgSAngrAZICwnfQARA/AAA/QAABGgUBIQAUhIAAhGQAAg/gRg/QgegzAKhFQAFgdAuABQCbiPAnghQBwhgBmg8IC5hkQAdgGAVgnQAmgMDWAoQDXApAqAcQArAeAvA4QAhAmA2BMQBNBmBPIEQggCOhnhUQhskBhkheQhphXhVh9QhbiziiAiQgTgEgTAAIAAAAIgBAAQhjAAhjCFIgBABIgCADIgBACIABgCIACgDIABgBQBjiFBjAAIABAAIAAAAQATAAATAEIgRAFQhhBQiDBdQiLBghUAsQghAQgXAVQgUARgEALQAJBWgUCIQgPBogXBRQgOCDAuBSQAHANgGASQgDAKgIAPQhniDguiVQAuCVBnCDIAbAyQAPAhgPAhQgXAagYAAQgNAAgNgHgAo7I/QiVh1hegiQBeAiCVB1gAowIxQidh2hjgtQBjAtCdB2gAovH3QhIhrgNiaQANCaBIBrgApaCuQAagLAAhoQAAgigDgrQADArAAAiQAABogaALgAKhAGQgYgGgWhtQAWBtAYAGgALdlUQBEBsAPB0QgPh0hEhsQhEhrgfgbQAfAbBEBrgABynSIAAAAg");
	this.shape_7.setTransform(111.7,73.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(1,1,1).p("AAAgCQAAACAAAE");
	this.shape_8.setTransform(235.1,130.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,237.2,150.5);


(lib.body = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AE6AUQAABsg3BNQgZAhgmAJQgRADg5AAQgjAAgggcQgUgSgjgxQghgpgLgSQgSgeAAguQAAg8AMg7QAOhHAZgjQAcgpAWgPQAagRAlAAQAkAAAwAmQAoAgAhAtQA3BNAABqgABzmGQA/AqBIA1QBVA4AXBYQAIAgAICOQAFB5AmBVQA3B7CKBvQgXA1gjARQgZAMgzABQgiAAgYABQgXACgOACQg8AMg2AnQgVg0hSghQhAgah8gWQiZgYhRgOQiOgYhbgeQA1gOAXgQQAfgVAUgsQhShIg8iBQhFiUgijbQAGipBuiHQC8gpDeB0QAOAIAPAIQBHApBiBEQiBgYhDAYQggAjgSBhQgPBNAABGQhHCeh1gqQhCg7g3heQg9hqAKg+QAJg6BChOQBIhUA3AKID6AbAGiIjIBZgtAGJHRQBBgFBbAHAENH2QAngeBVgHAFRH2IA4glAi/F5QAtAPA0ALQAxAKBmAUQBdAUBFAYAl7FtQAUgkCoAwAlsEaQBDA7BqAkAjsBcQDCDuEeAe");
	this.shape.setTransform(61,60.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FEFECB","#CC9933","#4B2D0F","#663300"],[0,0.349,0.722,0.902],31.2,-44,0,31.2,-44,93.3).s().p("AiJEGQhDg9g2heQg9hqAJg8QAJg6BChOQBIhUA4AKID3AbQBKAqBiBDQiEgXhDAXQgfAjgTBhQgOBLgBBGQg2B/hVAAQgWAAgYgJg");
	this.shape_1.setTransform(41.4,34.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#663300").s().p("AhEDsQgVgSgjgwQgigpgLgTQgSgeAAgtQAAg9ALg7QAOhGAagkQAdgpAWgPQAagRAmAAQAiAAAvAnQApAfAgAtQA3BNAABrQAABrg3BNQgYAhgnAJQgQAEg3gBQgkAAgfgcg");
	this.shape_2.setTransform(73.6,58.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#F9C519","#003300","#643007","#330000"],[0.051,0.243,0.553,1],-58.9,15.8,59,-15.7).s().p("ACkIFQhAgah8gWIjqgmQiOgYhbgeQA1gOAXgQQAfgVAUgsQBDA6BqAlQAtAPA0ALICXAeQBdAUBFAYQhFgYhdgUIiXgeQg0gLgtgPQhqglhDg6QhShIg8iBQhFiUgijbQAGipBuiHQC8gpDeB0IAdAQIj6gbQg3gKhIBUQhCBOgJA6QgKA+A9BqQA3BeBCA7QB1AqBHieQAAhGAPhNQAShhAggjQBDgYCCAYQA+AqBIA1QBVA4AXBYQAIAgAICOQAFB5AmBVQA3B7CKBvQgXA1gjARQgZAMgzABQgiAAgYABIBZgtIhZAtQgXACgOACQg8AMg2AnQgVg0hSghgAFRH2IA4glgAGJHRQhVAHgnAeQAngeBVgHIAEAAIAAAAIACAAQAYgCAcAAIAAAAIABAAQAnAAAuADIAMABIgMgBQgugDgnAAIgBAAIAAAAQgcAAgYACIgCAAIAAAAIgEAAgAi/F5IgIgDIgBAAIgGgCIgBAAIgBAAIgJgDIgDAAIgBgBQhCgRgngBIgIgBIAAAAQgjAAgJAPIAAAAIgBABIABgBIAAAAQAJgPAjAAIAAAAIAIABQAnABBCARIABABIADAAIAJADIABAAIABAAIAGACIABAAIAIADIAAAAgAD0FoQkegejCjuQDCDuEeAegAAnkFQgWAPgcApQgZAjgOBHQgMA7AAA8QAAAuASAeQALASAhApQAjAxAUASQAgAcAjAAQA5AAARgDQAmgJAZghQA3hNAAhsQAAhqg3hNQghgtgoggQgwgmgkAAQglAAgaARgAGiIjg");
	this.shape_3.setTransform(61,60.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,124.1,122.5);


// stage content:
(lib.white = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// head
	this.instance = new lib.head();
	this.instance.setTransform(266,130.3,1,1,0,0,0,45.3,70.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:267.4,y:120.3},3).to({x:266,y:130.3},4).to({x:267.4,y:134.5},4).to({x:266,y:130.3},3).wait(1));

	// kist_r
	this.instance_1 = new lib.kist_r();
	this.instance_1.setTransform(279.7,216.5,1,1,0,0,0,29.2,16.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(3).to({regX:48.3,rotation:-15,x:298.7,y:223.5},0).to({x:314.5,y:220.7},4).to({x:298.7,y:223.5},4).wait(3).to({regX:29.2,rotation:0,x:279.7,y:216.5},0).wait(1));

	// hand_r
	this.instance_2 = new lib.hand_r();
	this.instance_2.setTransform(316.8,162.6,1,1,0,0,0,28.9,61.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({rotation:-15,x:324.8,y:161},7).to({rotation:0,x:316.8,y:162.6},7).wait(1));

	// kist_l
	this.instance_3 = new lib.kist_l();
	this.instance_3.setTransform(177.5,133.6,1,1,0,0,0,14.9,17.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:203.4,y:142.5},7).to({x:177.5,y:133.6},7).wait(1));

	// gitar
	this.instance_4 = new lib.gitar();
	this.instance_4.setTransform(218.1,205,1,1,0,0,0,97.1,107.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:97.2,regY:108,rotation:10.5,y:192.1},7).to({regX:97.1,regY:107.9,rotation:0,y:205},7).wait(1));

	// hand_l
	this.instance_5 = new lib.hand_l();
	this.instance_5.setTransform(214,136,1,1,0,0,0,44.7,18.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({regX:44.6,regY:18.6,rotation:-30,x:236.4,y:122.2},7).to({regX:44.7,regY:18.5,rotation:0,x:214,y:136},7).wait(1));

	// body
	this.instance_6 = new lib.body();
	this.instance_6.setTransform(292.5,140,1,1,0,0,0,61,60.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({regX:61.2,regY:60.4,rotation:1.3,x:306.5,y:141.3},7).to({regX:61,regY:60.2,rotation:0,x:292.5,y:140},7).wait(1));

	// foot_r
	this.instance_7 = new lib.foot_r();
	this.instance_7.setTransform(373.4,275.3,1,1,0,0,0,32.3,47.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(15));

	// foot_l
	this.instance_8 = new lib.foot_l();
	this.instance_8.setTransform(185.5,294.8,1,1,0,0,0,27.7,140.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({regX:27.8,rotation:2.3,x:185.7},7).to({regX:27.7,rotation:0,x:185.5},7).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(395.5,259,285.8,264.3);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;